apiVersion: v1
kind: Service
metadata:
  name: go-file-server-service
  labels:
    app: go-file-server
  namespace: services
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31080
      targetPort: 8080
      protocol: TCP
  selector:
    app: go-file-server

